package io.shapez.game;

public enum HubGoalReward {
    RewardCutterAndTrash,
    RewardRotator,
    RewardPainter,
    RewardMixer,
    RewardStacker,
    RewardBalancer,
    RewardTunnel,
    RewardRotatorCcw,
    RewardRotator180,
    RewardMinerChainable,
    RewardUndergroundBeltTier2,
    RewardBeltReader,
    RewardSplitter,
    RewardCutterQuad,
    RewardPainterDouble,
    RewardStorage,
    RewardMerger,
    RewardWiresPaintersAndLevers,
    RewardDisplay,
    RewardConstantSignal,
    RewardLogicGates,
    RewardVirtualProcessing,
    RewardFilter,
    RewardDemoEnd,
    RewardBlueprints,
    RewardFreeplay,
    NoReward,
    NoRewardFreeplay,
}
